output_path: dummy-tracking-env/rl_study
mode: param_study
number_of_jobs:  # indicates number of seeds per parameter value
  - 3
base_config_files:
  - src/scripts/config/rl_tracking_ppo.yml
job_configs:
  - command: python3.8 src/scripts/experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase-dummy-tracking-env
    cpus: 2
    gpus: 1
    cpu_mem_gb: 5
    disk_mem_gb: 52
    wall_time_s: 1 * 60 * 60
    nice: true
    gpu_mem_mb: 1900
    use_singularity: false
    check_if_ros_already_in_use: false
    save_locally: true
