output_path: cone_world
mode: data_collection
job_configs:
  - command: python3.8 src/scripts/data_collection_gazebo.py
    codebase_dir: /users/students/r0667559/code/imitation-learning-codebase
    cpus: 11
    gpus: 0
    cpu_mem_gb: 4
    disk_mem_gb: 8
    wall_time_s: 10 * 60
    nice: false
    priority: -10
    use_singularity: true
    check_if_ros_already_in_use: false
    save_locally: true
    extra_requirements: ( Mips >= 26000 )
number_of_jobs:
  - 1
base_config_files:
  - src/scripts/config/il_data_collection_cone_world.yml