output_path: cone_training/sgd
mode: train
job_configs:
  - command: python3.8 src/scripts/experiment.py
    codebase_dir: /users/students/r0667559/code/imitation-learning-codebase
    cpus: 4
    gpus: 1
    cpu_mem_gb: 16
    disk_mem_gb: 52
    wall_time_s: 60 * 5
    nice: true
    gpu_mem_mb: 4000
    use_singularity: false
    check_if_ros_already_in_use: false
    save_locally: false
number_of_jobs:
  - 1
base_config_files:
  - src/scripts/config/il_train_cone_world.yml
