output_path: /media/thomas/Elements/training_nn/test_bebop_proj_3_mse
number_of_epochs: 1
episode_runner_config:
  number_of_episodes: 1
architecture_config:
  architecture: bebop_400_arch_2
  device: cpu
load_checkpoint_dir: /media/thomas/Elements/training_nn/bebop_high_res/net_str_1_new_ARCH_5
evaluator_config:
  split_losses: true
  data_loader_config:
    hdf5_files:
      - /media/thomas/Elements/experimental_data/bebop_high_res/data_collection_gazebo/validation.hdf5
    random_seed: 123
    balance_over_actions: false
    batch_size: 1
    input_size: [1, 240, 428]
  store_projected_output_on_tensorboard: true
  criterion: MSELoss
  device: cuda
tensorboard: true