output_path: encoder_decoder/textured/models/default/auto_encoder_conv1/lr_0.001
number_of_epochs: 0
number_of_episodes: 1
architecture_config:
  architecture: auto_encoder_conv1
  device: cuda
evaluator_config:
  data_loader_config:
    hdf5_files:
      - hdf5_files/line_world/real/1_64_64/validation_0.hdf5
    random_seed: 123
    balance_over_actions: false
    batch_size: 64
    input_size: [1, 64, 64]
  criterion: MSELoss
  device: cuda
  store_output_on_tensorboard: true
  evaluate_extensive: true
tensorboard: true