output_path: /media/thomas/Elements/training_nn/multi_cone_1_out
number_of_epochs: 100
episode_runner_config:
  number_of_episodes: -1
save_checkpoint_every_n: 10
architecture_config:
  architecture: simple_cone_architecture
  initialisation_type: xavier
  random_seed: 123
  device: cpu
  dropout: default
  dtype: default
  log_std: default
trainer_config:
  optimizer: Adam
  learning_rate: 0.0005
  weight_decay: 0.00001
  factory_key: BASE
  gradient_clip_norm: -1
  data_loader_config:
    hdf5_files:
      - /media/thomas/Elements/experimental_data/multiple_cones/data_collection_gazebo/train.hdf5
    random_seed: 123
    balance_over_actions: false
    batch_size: 2
  criterion: MSELoss
  device: cuda
evaluator_config:
  data_loader_config:
    hdf5_files:
      - /media/thomas/Elements/experimental_data/multiple_cones/data_collection_gazebo/validation.hdf5
    random_seed: 123
    balance_over_actions: false
    batch_size: 2
  criterion: MSELoss
  store_projected_output_on_tensorboard: false
  device: cuda
tensorboard: true