output_path: test_encoder_decoder
number_of_epochs: 100
number_of_episodes: -1
save_checkpoint_every_n: 99
architecture_config:
  architecture: auto_encoder_deeply_supervised
  initialisation_type: xavier
  random_seed: 4
  device: cuda
  dropout: default
  batch_normalisation: default
  vae: false
  dtype: default
  log_std: default
trainer_config:
  optimizer: Adam
  learning_rate: 0.001
  factory_key: DeepSupervision
  add_KL_divergence_loss: false
  data_loader_config:
    loop_over_hdf5_files: true
    hdf5_files:
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_0.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_10.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_11.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_12.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_13.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_14.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_1.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_2.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_3.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_4.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_5.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_6.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_7.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_8.hdf5
      - /gluster/visics/kkelchte/line_world_data/sim/textured/1_200_200/train_9.hdf5
    random_seed: 123
    balance_over_actions: false
    batch_size: 32
  criterion: WeightedBinaryCrossEntropyLoss
  criterion_args_str: 'beta=0.9'
  device: cuda
  store_output_on_tensorboard: true
evaluator_config:
  data_loader_config:
    hdf5_files:
      -  /gluster/visics/kkelchte/line_world_data/real/1_200_200/validation_0.hdf5
    random_seed: 32
    balance_over_actions: false
    batch_size: 32
  criterion: MSELoss
  device: cuda
  store_output_on_tensorboard: true
  evaluate_extensive: true
tensorboard: true
